// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASnvV134N_Rt9CSz13r-CPzM9yDGfaMaU',
    appId: '1:211839032136:web:0cc4ef74b061bc88bf317d',
    messagingSenderId: '211839032136',
    projectId: 'biblioteca-8755c',
    authDomain: 'biblioteca-8755c.firebaseapp.com',
    storageBucket: 'biblioteca-8755c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyFjDlPEkpsK_15geIJ6wHh6UsPV2z5q4',
    appId: '1:211839032136:android:1f3fdb244be6b1bcbf317d',
    messagingSenderId: '211839032136',
    projectId: 'biblioteca-8755c',
    storageBucket: 'biblioteca-8755c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDzwpm-3PwANnVnhYIEhDA7MC0vCDOYGg',
    appId: '1:211839032136:ios:10db1a9eabc10d0bbf317d',
    messagingSenderId: '211839032136',
    projectId: 'biblioteca-8755c',
    storageBucket: 'biblioteca-8755c.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDzwpm-3PwANnVnhYIEhDA7MC0vCDOYGg',
    appId: '1:211839032136:ios:10db1a9eabc10d0bbf317d',
    messagingSenderId: '211839032136',
    projectId: 'biblioteca-8755c',
    storageBucket: 'biblioteca-8755c.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASnvV134N_Rt9CSz13r-CPzM9yDGfaMaU',
    appId: '1:211839032136:web:4291408385e9ef99bf317d',
    messagingSenderId: '211839032136',
    projectId: 'biblioteca-8755c',
    authDomain: 'biblioteca-8755c.firebaseapp.com',
    storageBucket: 'biblioteca-8755c.firebasestorage.app',
  );
}
